### PR TITLE
Made space for config menu in top bar of gui on small screens

### PR DESCRIPTION
**Pull request by ghost**
On smaller screens such as iPad the config menu disappears off the right of the screen. This is because of the removal of the donate button from the original interface. I have just made an empty space where the button used to be to correct it.

### CODE REVIEW

**Comment by fernandog** [comment]
@joshjowen can you confirm that in small screens (phone) the top bar MENU button is not re-sizing. I doesn't appear in the screen if you zoom in ? It only appears if you fully zoom out

**Comment by joshjowen** [comment]
@fernandog Absolutely confirmed, When I open sickrage on my phone it appears like the attached image and I need to zoom out to see the button (also the whole page). This screeshot was taken on "BRANCH: (develop) / COMMIT: (c62d8f2c799edd7daad5648f45276a3464d83a9e)"
screenshot_2015-02-10-15-07-44

**Comment by fernandog** [comment]
Do you know how to fix it? I saw that jquery was updated. Maybe related?

**Comment by joshjowen** [comment]
I had a look through some of the code and was able to fix it on my phone (Sony xperia Z2), my wife's iPhone 6 and her iPad with the fix here: "https://github.com/joshjowen/SickRage/compare/SiCKRAGETV:develop...gui-scale-issue" I could make a pull request if you think it is worthwhile

**Comment by fernandog** [comment]
@joshjowen with this my SR opens as in desktop mode. I don't recognize as a phone, so there's no menu button.

**Comment by fernandog** [comment]
@joshjowen using the extension "Mobile/Responsive Web Design Tester" and simulating a Galaxy S5 it works. But on my real phone it doesn't. Really strange

screen

**Comment by abeloin** [comment]
@fernandog http://www.responsinator.com can be useful

**Comment by abeloin** [comment]
By the way, there's a typo in the code(") and initial-scale should be in content:
```<meta name="viewport" initial-scale=1">```

**Comment by fernandog** [comment]
@abeloin even changing content is does not work.

<meta name="viewport" content="initial-scale=1">

**Comment by fernandog** [comment]
the original code is correct:
https://developers.google.com/speed/docs/insights/ConfigureViewport?hl=en

**Comment by abeloin** [comment]
@fernandog On your s5 are you using android browser or chrome?

**Comment by fernandog** [comment]
@abeloin chrome for android.

**Comment by abeloin** [comment]
@fernandog Can you try the reference implementation to see if it work?
http://getbootstrap.com/examples/navbar/

**Comment by fernandog** [comment]
@abeloin it don't get re-sized when I zoom-in.

**Comment by abeloin** [comment]
@fernandog I'm not sure to understand. You don't see the menu on the right side?

**Comment by fernandog** [comment]
https://carousel.dropbox.com/photos/cc/y2EzlHEXwfAQeGV

If I zoom in the navbar dont resize.

Desktop chrome it does.

**Comment by abeloin** [comment]
That's the normal behavior, you're zooming in the page. Desktop Chrome Zoom() != android/iphone/ipad zoom.

See answer about this on https://github.com/twbs/bootstrap/issues/5923

**Comment by abeloin** [comment]
@fernandog Is this what you expect it to be, see image?

**Pull request merged**
