### PR TITLE
Fix recursion in status strings and raise appropriate KeyErrors...

### PR DESCRIPTION
**Pull request by labrys**
…TypeErrors

-Switched to long() conversion to avoid recursion when numeric key > int.  
-Raising appropriate TypeErrors and KeyErrors.
-Added views

### CODE REVIEW

**Comment by labrys** [comment]
Tested it against master and it appears to work well.  Dev is too broke for me to test... shows don't display anything since the encoding hack was removed.

**Comment by miigotu** [comment]
We should probably add some strong unit testing for this

**Comment by fernandog** [comment]
@miigot what about this one? merge or need further tests/changes?

**Comment by labrys** [comment]
I've been running this with no issues for a while now, so in my opinion it should be fine to merge.

I'm working on streamlining it, making it Python 3+ compatible, and adding unit tests if you want to wait, though.

**Comment by fernandog** [comment]
Nice!

**Pull request closed without merging**
